name: dls_workshop_backend            # default is root
channels:
- pytorch
- conda-forge
dependencies:         # everything under this, installed by conda
- pip
- pandas==1.5.1
- pydantic==2.5.1
- scikit-learn==1.3.2
- pip:                # everything under this, installed by pip
  - fastapi==0.103.0
  - uvicorn==0.23.0
  - uvloop==0.17.0
  - pydantic-settings==2.0.2